

SET(THIRDPARTY_DIR  ${PROJECT_SOURCE_DIR}/3rdParty_x64)

FIND_PATH(THIRDPARTY_INCLUDE_DIR pthread.h
  PATH_SUFFIXES inc include Frameworks 
  HINTS
  ${THIRDPARTY_DIR}
)
MARK_AS_ADVANCED(THIRDPARTY_INCLUDE_DIR)

MACRO(FIND_THIRDPARTY_LIBRARY MYLIBRARY MYLIBRARYNAME)
  FIND_LIBRARY(${MYLIBRARY}
    NAMES ${MYLIBRARYNAME}
    PATH_SUFFIXES lib build/lib lib64 build/lib64 Frameworks
    PATHS
	${THIRDPARTY_DIR}
)
  MARK_AS_ADVANCED(${MYLIBRARY})
ENDMACRO(FIND_THIRDPARTY_LIBRARY LIBRARY LIBRARYNAME)

# Find release (optimized) libs
FIND_THIRDPARTY_LIBRARY(GLEW_LIBRARY glew32)
FIND_THIRDPARTY_LIBRARY(GLEW_STATIC_LIBRARY glew32s)

FIND_THIRDPARTY_LIBRARY(GLFW_LIBRARY GLFWDLL)
FIND_THIRDPARTY_LIBRARY(GLFW3_LIBRARY glfw3)
FIND_THIRDPARTY_LIBRARY(GLFW3_LIBRARY_DLL glfw3DLL)


FIND_THIRDPARTY_LIBRARY(FREEGLUT_LIBRARY freeglut)
FIND_THIRDPARTY_LIBRARY(GLUT_LIBRARY glut32)
FIND_THIRDPARTY_LIBRARY(PTHREADS_LIBRARY pthreadVC2)
FIND_THIRDPARTY_LIBRARY(AntTweakBar_LIBRARY AntTweakBar64)
FIND_THIRDPARTY_LIBRARY(TIFF_LIBRARY tiff)
FIND_THIRDPARTY_LIBRARY(SDL_LIBRARY SDL)
FIND_THIRDPARTY_LIBRARY(FREETYPE_LIBRARY freetype271)
FIND_THIRDPARTY_LIBRARY(SDL2_LIBRARY SDL2)
FIND_THIRDPARTY_LIBRARY(SDL2main_LIBRARY SDL2main)
FIND_THIRDPARTY_LIBRARY(LIBPNG_LIBRARY libpng16_static)
FIND_THIRDPARTY_LIBRARY(SOIL_LIBRARY SOIL)

FIND_THIRDPARTY_LIBRARY(jpeg_LIBRARY jpeg)
FIND_THIRDPARTY_LIBRARY(gdal_i_LIBRARY gdal_i)
FIND_THIRDPARTY_LIBRARY(CURL_LIBRARY libcurl_imp)



# Find debug libs
FIND_THIRDPARTY_LIBRARY(GLEW_LIBRARY_DEBUG glew32)
FIND_THIRDPARTY_LIBRARY(GLEW_STATIC_LIBRARY_DEBUG glew32s)

FIND_THIRDPARTY_LIBRARY(GLFW_LIBRARY_DEBUG GLFWDLL)
FIND_THIRDPARTY_LIBRARY(GLFW3_LIBRARY_DEBUG glfw3d)
FIND_THIRDPARTY_LIBRARY(GLFW3_LIBRARY_DLL_DEBUG glfw3DLL)

FIND_THIRDPARTY_LIBRARY(FREEGLUT_LIBRARY_DEBUG freeglutd)
FIND_THIRDPARTY_LIBRARY(GLUT_LIBRARY_DEBUG glut32d)

FIND_THIRDPARTY_LIBRARY(PTHREADS_LIBRARY_DEBUG pthreadVC2)

FIND_THIRDPARTY_LIBRARY(AntTweakBar_LIBRARY_DEBUG AntTweakBar64)
FIND_THIRDPARTY_LIBRARY(TIFF_LIBRARY_DEBUG tiffd)

FIND_THIRDPARTY_LIBRARY(SDL_LIBRARY_DEBUG SDL)
FIND_THIRDPARTY_LIBRARY(FREETYPE_LIBRARY_DEBUG freetype271d)
FIND_THIRDPARTY_LIBRARY(SDL2_LIBRARY_DEBUG SDL2)
FIND_THIRDPARTY_LIBRARY(SDL2main_LIBRARY_DEBUG SDL2main)

FIND_THIRDPARTY_LIBRARY(LIBPNG_LIBRARY_DEBUG libpng16_staticd)
FIND_THIRDPARTY_LIBRARY(SOIL_LIBRARY_DEBUG SOIL)

FIND_THIRDPARTY_LIBRARY(jpeg_LIBRARY_DEBUG jpegd)

FIND_THIRDPARTY_LIBRARY(gdal_i_LIBRARY_DEBUG gdal_i)
FIND_THIRDPARTY_LIBRARY(CURL_LIBRARY_DEBUG libcurl_impd)
